[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyH2A"
version = "0.1.0"
dependencies = [
    "python-json-logger",
    "pytest",
    "click>=7.1.2",
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "numpydoc",
    "autodocsumm",
    "furo"
]

[tool.setuptools]
packages = ["pyH2A"]
