[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyH2A"
description = "pyH2A is an extensible Python framework for the analysis of hydrogen production cost. Its discounted cash flow module is based on the H2A Hydrogen Analysis model developed by the U.S. Department of Energy"
version = "v0.0a8"
readme = "README.md"
requires-python = ">= 3.9"
dependencies = [
    "autodocsumm>=0.2.14",
    "autopep8>=2.3.2",
    "click>=8.1.8",
    "furo>=2025.9.25",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "numpydoc>=1.9.0",
    "pandas>=2.3.3",
    "pint>=0.24.4",
    "pytest>=8.4.2",
    "scipy>=1.13.1",
]

[project.optional-dependencies]
performance = [
    "pypardiso>=0.4.7; sys_platform == 'win32' or sys_platform == 'linux'",
    "scikit-umfpack>=0.3.3; sys_platform == 'darwin'",
]

[project.scripts]
pyH2A = "pyH2A.cli_pyH2A:cli"
