"""LCA Monte Carlo regression test — seed=42, 10 samples.

Fixes the GWP100 response surface for two varied foreground components of the
PVE GT toy model.  Any change to the LCA solver, Sherman-Morrison update, or
parameter-application path that shifts these values signals a regression.

Matrix:  src/tests/lca/LCA_Test_PVE_GT
Inputs:  src/tests/lca/input_files/PVE_GT_S1.md (base case DCF + LCA)

Parameters varied (seed=42, uniform):
  PV Electricity Generation  ~ Uniform(100, 300) MJ / kg H2
  Reverse Osmosis            ~ Uniform(5,   15)  kg / kg H2
"""
from pathlib import Path

import numpy as np
import pytest
from pyH2A.LCA.LCA import LCA
from pyH2A.Utilities.lca_utils import get_cache_paths
from pyH2A.Utilities.input_modification import convert_input_to_dictionary
from pyH2A.Analysis.Monte_Carlo_Analysis import _mc_response_worker

# ── Paths ──────────────────────────────────────────────────────────────────────

_HERE = Path(__file__).parent
_INPUT_FILE = _HERE / 'input_files' / 'PVE_GT_S1.md'

_GWP100_KEY = 'Climate change no LT - Global warming potential (GWP100) no LT'

# ── MC configuration ───────────────────────────────────────────────────────────

_SEED = 42
_N_SAMPLES = 10

_PARAMETERS = {
    'PV (MJ/kg H2)': {
        'Parameter': ['LCA - PVE GT Components', 'PV Electricity Generation', 'Value'],
        'Index': 0,
        'Type': 'value',
    },
    'RO (kg/kg H2)': {
        'Parameter': ['LCA - PVE GT Components', 'Reverse Osmosis', 'Value'],
        'Index': 1,
        'Type': 'value',
    },
}

# Reference GWP100 values (kg CO2-Eq / kg H2) captured with seed=42.
# Generated by np.random.default_rng(42) with PV ~ Uniform(100, 300) and
# RO ~ Uniform(5, 15).  Update these only when the LCA computation
# intentionally changes.
_REFERENCE_GWP100 = np.array([
    0.5839992135992145,
    0.4314553037556835,
    0.6230905504249669,
    0.5495711033843045,
    0.2731058402523933,
    0.6760655809273816,
    0.5783839568688932,
    0.5891242344961632,
    0.2891499550877110,
    0.4363215204690081,
])


# ── Cache management ───────────────────────────────────────────────────────────

def _clear_ram_cache():
    for k in LCA._cache:
        LCA._cache[k] = None
    get_cache_paths.cache_clear()


@pytest.fixture(scope='module', autouse=True)
def _manage_lca_caches():
    """Clear RAM before the regression run; keep disk cache warm for reuse."""
    _clear_ram_cache()
    yield
    _clear_ram_cache()


# ── Regression test ────────────────────────────────────────────────────────────

class TestMCLCARegressionSeed42:
    """GWP100 regression for 10 seeded MC samples against LCA_Test_PVE_GT.

    Calls _mc_response_worker directly (single process, no executor overhead)
    so the test is fast and fully deterministic.  The same code path executes
    inside worker processes during a real multiprocessing run.
    """

    def _generate_values(self):
        rng = np.random.default_rng(_SEED)
        pv = rng.uniform(100.0, 300.0, _N_SAMPLES)
        ro = rng.uniform(5.0, 15.0, _N_SAMPLES)
        return np.column_stack([pv, ro])

    def test_gwp100_matches_reference(self):
        inp = convert_input_to_dictionary(str(_INPUT_FILE))
        values = self._generate_values()
        results = _mc_response_worker(values, inp, _PARAMETERS, _GWP100_KEY)
        np.testing.assert_allclose(results, _REFERENCE_GWP100, rtol=1e-5)

    def test_all_gwp100_values_are_positive_and_finite(self):
        inp = convert_input_to_dictionary(str(_INPUT_FILE))
        values = self._generate_values()
        results = _mc_response_worker(values, inp, _PARAMETERS, _GWP100_KEY)
        assert all(np.isfinite(v) and v > 0 for v in results)

    def test_gwp100_spans_expected_physical_range(self):
        """Values must lie between the single-component openLCA GT bounds."""
        # Lowest scenario in GT suite: S4 ≈ 0.229 (PV=100 MJ, RO=5 kg)
        # Highest scenario in GT suite: S5 ≈ 0.688 (PV=300 MJ, RO=15 kg)
        assert min(_REFERENCE_GWP100) > 0.20
        assert max(_REFERENCE_GWP100) < 0.75
