CONFIG = {   't': {'dimension': 'mass',
                      'unit': 'ton',
                      'reference': None},

              'CTUe': {'dimension': 'dimensionless',
                       'unit': '-',
                       'reference': "['CTUe']"},
              'CTUh': {'dimension': 'dimensionless',
                       'unit': '-',
                       'reference': "['CTUh']"},
              'dimensionless': {'dimension': 'dimensionless',
                                 'unit': '-',
                                 'reference': None},
              'disease incidence': {'dimension': 'dimensionless',
                                     'unit': '-',
                                     'reference': "['disease incidence']"},
              'kBq U235-Eq': {'dimension': 'radioactivity',
                               'unit': 'kBq',
                               'reference': "['U235-Eq']"},
              'kg CFC-11-Eq': {'dimension': 'mass',
                                'unit': 'kg',
                                'reference': "['CFC-11-Eq']"},
              'kg CO2-Eq': {'dimension': 'mass',
                            'unit': 'kg',
                            'reference': "['CO2-Eq']"},
              'kg SO2-Eq': {'dimension': 'mass',
                            'unit': 'kg',
                            'reference': "['SO2-Eq']"},
              'kg CO2-eq': {'dimension': 'mass',
                            'unit': 'kg',
                            'reference': "['CO2-eq']"},
              'kg SO2-eq': {'dimension': 'mass',
                            'unit': 'kg',
                            'reference': "['SO2-eq']"},
              'kg N-Eq': {'dimension': 'mass',
                          'unit': 'kg',
                          'reference': "['N-Eq']"},
              'kg NMVOC-Eq': {'dimension': 'mass',
                               'unit': 'kg',
                               'reference': "['NMVOC-Eq']"},
              'kg P-Eq': {'dimension': 'mass',
                          'unit': 'kg',
                          'reference': "['P-Eq']"},
              'kg Sb-Eq': {'dimension': 'mass',
                           'unit': 'kg',
                           'reference': "['Sb-Eq']"},
              'kWh': {'dimension': 'energy',
                      'unit': 'kWh',
                      'reference': None},
              'm3 world Eq deprived': {'dimension': 'volume',
                                       'unit': 'm3',
                                       'reference': "['world Eq deprived']"},
              'MJ': {'dimension': 'energy',
                     'unit': 'MJ',
                     'reference': None},
              'MJ, net calorific value': {'dimension': 'energy',
                                          'unit': 'MJ',
                                          'reference': "['net calorific value']"},
              'MJ-Eq': {'dimension': 'energy',
                        'unit': 'MJ',
                        'reference': "['-Eq']"},
              'mol H+-Eq': {'dimension': 'substance',
                            'unit': 'mol',
                            'reference': "['H+-Eq']"},
              'mol N-Eq': {'dimension': 'substance',
                           'unit': 'mol',
                           'reference': "['N-Eq']"},
            }
